function [r] = volume_3( s, i, j, k )

global x_dim y_dim z_dim occupation seen;

if i < 1 || i > y_dim || j < 1 || j > x_dim || k < 1 || k > z_dim
    r = 0;
else
    ct = occupation{s}(i,j,k);
    if seen{s}(i,j,k)
        r = 0;
    elseif ct == 4 || ct == 5
        r = 0;
    elseif ct == 1 || ct == 3
        seen{s}(i,j,k) = 1;
        r = 1 + volume_3(s, i-1, j-1, k-1) ...
              + volume_3(s, i-1, j  , k-1) ...
              + volume_3(s, i-1, j+1, k-1) ...
              + volume_3(s, i  , j-1, k-1) ...
              + volume_3(s, i  , j  , k-1) ...
              + volume_3(s, i  , j+1, k-1) ...
              + volume_3(s, i+1, j-1, k-1) ...
              + volume_3(s, i+1, j  , k-1) ...
              + volume_3(s, i+1, j+1, k-1) ...
              + volume_3(s, i-1, j-1, k  ) ...
              + volume_3(s, i-1, j  , k  ) ...
              + volume_3(s, i-1, j+1, k  ) ...
              + volume_3(s, i  , j-1, k  ) ...
              + volume_3(s, i  , j+1, k  ) ...
              + volume_3(s, i+1, j-1, k  ) ...
              + volume_3(s, i+1, j  , k  ) ...
              + volume_3(s, i+1, j+1, k  ) ...
              + volume_3(s, i-1, j-1, k+1) ...
              + volume_3(s, i-1, j  , k+1) ...
              + volume_3(s, i-1, j+1, k+1) ...
              + volume_3(s, i  , j-1, k+1) ...
              + volume_3(s, i  , j  , k+1) ...
              + volume_3(s, i  , j+1, k+1) ...
              + volume_3(s, i+1, j-1, k+1) ...
              + volume_3(s, i+1, j  , k+1) ...
              + volume_3(s, i+1, j+1, k+1) ;
    else
        r = 0;
    end
end

return;

end